#! /usr/bin/env python
# encoding: utf-8
# Sandeep S Srinivasa, 2009
from Logs import error, debug, warn

include_dirs = """
                 include 
                 #lib/libavl/include 
                 #lib/libnvpair/include 
                 #lib/libumem/include
                 """.split()

include_dirs_kernel = """
                      #lib/libsolkerncompat/include
                      """.split()

include_dirs_user = """
                     #lib/libzpool/include 
                     #lib/libsolcompat/include
                    """.split()

##########################################

obj_user = bld.new_task_gen(
        features = 'cc cstaticlib',
        includes = include_dirs + include_dirs_user,
        defines = ['_FILE_OFFSET_BITS=64', 'TEXT_DOMAIN=\"zfs-fuse\"'],
        target = 'zfscommon-user'
        )


obj_user.find_sources_in_dirs('.') # take the sources in the current folder

obj_kernel = bld.new_task_gen(
        features = 'cc cstaticlib',
        includes = include_dirs + include_dirs_kernel,
        defines = [ '_KERNEL', '_FILE_OFFSET_BITS=64', 'TEXT_DOMAIN=\"zfs-fuse\"'],
        target = 'zfscommon-kernel'
        )

obj_kernel.find_sources_in_dirs('.') # take the sources in the current folder

