#! /usr/bin/env python
# encoding: utf-8
# Sandeep S Srinivasa, 2009
from Logs import error, debug, warn

include_dirs = """
                #lib/libavl/include 
                #lib/libnvpair/include 
                #lib/libumem/include 
                #lib/libzfscommon/include 
                #lib/libsolkerncompat/include
               """.split()

obj = bld.new_task_gen(
        features = 'cc cprogram',
        includes = include_dirs,
        defines = [ '_FILE_OFFSET_BITS=64', '_KERNEL'],
        uselib_local = 'zpool-kernel zfscommon-kernel nvpair-kernel avl umem solkerncompat',
        uselib = 'aio_lib fuse_lib dl z pthread_lib rt_lib',
        target = 'zfs-fuse'
        )


obj.find_sources_in_dirs('.') # take the sources in the current folder

