#! /usr/bin/env python
# encoding: utf-8
# Sandeep S Srinivasa, 2009
from Logs import error, debug, warn

include_dirs = """
                 #lib/libuutil/include 
                 #lib/libnvpair/include 
                 #lib/libumem/include 
                 #lib/libzfscommon/include 
                 #lib/libzfs/include 
                 #lib/libsolcompat/include 
                 #lib/libavl/include 
                 ../stat/common
               """.split()

obj = bld.new_task_gen(
        features = 'cc cprogram',
        includes = include_dirs,
        defines = [ '_FILE_OFFSET_BITS=64', 'TEXT_DOMAIN=\"zfs-fuse\"'],
        uselib_local = 'nvpair-user umem zfs-lib zfscommon-user uutil avl solcompat',
        uselib = 'pthread_lib m_lib dl_lib',
        name = 'zpool',
        target = 'zpool'
        )


obj.find_sources_in_dirs('.') # take the sources in the current folder

obj.source = obj.source + ['../stat/common/timestamp.c']

